<?php

/**
 * Implements hook_page_build().
 */
function lift_modal_page_build(&$page) {

  // In-place editing is only supported on the front-end.
  if (path_is_admin(current_path())) {
    return;
  }

  $id = $_COOKIE['tc_ptid'];
  $lib = libraries_load('acquia-lift-rest');
  $api = new acquia_lift_api_visitor_query();
  $api->setIdentity($id, 'tracking');
  $api->addRequest(array('personTables' => 'person,identifiers'));
  $result = $api->execute();

  $grav_url = "https://www.gravatar.com/avatar/" . md5('nothing@example.com') . "?d=mm" . "&s=100x100";
  $settings = array('lift_modal' => array(
    'first' => date('c'),
    'last' => date('c'),
    'engagement' => 1,
    'image' => $grav_url,
    'debug' => $result,
  ));

  if ($result->code == 200) {

    $person = $result->data['person'];
    $settings['lift_modal']['engagement'] = $person['engagementScore'] + 1;
    $settings['lift_modal']['first'] = $person['firstTouch'];
    $settings['lift_modal']['last'] = $person['lastTouch'];
    $settings['lift_modal']['persona'] = $person['persona'];

    $identifiers = $result->data['identifiers'];

    foreach ($identifiers as $identifier) {
      // personIdentifierTypeId = 1 (email)
      // personIdentifierTypeId = 2 (Cookie ID)
      if ($identifier['identifier'] != $person['primaryIdentifier'] && strpos($identifier['identifier'], '@') !== false) {
        $settings['lift_modal']['email'] = $identifier['identifier'];
        if (isset($settings['lift_modal']['email'])) {
          $settings['lift_modal']['image'] = "https://www.gravatar.com/avatar/" . md5(strtolower(trim($settings['lift_modal']['email']))) . "?d=mm" . "&s=100x100";
          continue;
        }
      }
      elseif ($identifier['identifier'] != $person['primaryIdentifier'] && strpos($identifier['identifier'], ' ') !== false) {
        $settings['lift_modal']['name'] = $identifier['identifier'];
        continue;
      }
    }
  }

  drupal_add_js($settings, 'setting');
  drupal_add_library('lift_modal', 'modal');
}

/**
 * Implements hook_library().
 */
function lift_modal_library() {
  $path = drupal_get_path('module', 'lift_modal');

  $libraries['modal'] = array(
    'title' => 'Adds the Lift modal files.',
    'version' => VERSION,
    'js' => array(
      $path . '/js/lift_modal.js' => array(
        'type' => 'file',
        'scope' => 'header'
      ),
    ),
    'css' => array(
      $path . '/css/lift_modal.css' => array(),
    ),
    'dependencies' => array(
      array('acquia_lift', 'acquia_lift.v2_agent_api'),
    ),
  );

  return $libraries;
}
